name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check pre-commit-config file existence
        id: pre-commit
        run: |
          if [ -f ".pre-commit-config.yaml" ]; then
            echo "file-exists=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run pre-commit
        if: steps.pre-commit.outputs.file-exists
        uses: pre-commit/action@v3.0.0
